apiVersion: v1
kind: Secret
metadata:
  name: {{ include "entryserver.fullname" . }}-secret
  labels:
    {{- include "entryserver.labels" . | nindent 4 }}
type: Opaque
stringData:
  BRIDGE_API_KEY: {{ .Values.secretEnv.BRIDGE_API_KEY | quote }}
  ACTUAL_SERVER_URL: {{ .Values.secretEnv.ACTUAL_SERVER_URL | quote }}
  ACTUAL_PASSWORD: {{ .Values.secretEnv.ACTUAL_PASSWORD | quote }}
  ACTUAL_FILE_PASSWORD: {{ .Values.secretEnv.ACTUAL_FILE_PASSWORD | quote }}
